### ISSUE TITLE
Ajouter le support d'une couche ArcGIS rest dans le XML d'IGO

### ISSUE THREAD

**Issue by gignacnic** [infra-geo-ouverte/igo#116]
Il faudrait ajouter le support d'ajout de couche ArcGIS restful dans IGO, comme on peut le faire dans OpenLayers 2, voici un exemple :  

var layer = map.addLayer(new OpenLayers.Layer.ArcGIS93Rest( "Nom du Layers",  "http://sampleserver1.arcgisonline.com/ArcGIS/rest/services/Specialty/ESRI_StateCityHighway_USA/MapServer/export", 
                    {layers: "show:0,2", projection: new OpenLayers.Projection("EPSG:3857".toUpperCase()),}));

ou 

var layer = map.addLayer(new OpenLayers.Layer.ArcGIS93Rest( "ArcGIS Server Layer",  "http://gis.ijc.org/arcgis/rest/services/ChamplainScenarios/Scenario_2/MapServer/export", 
                    {layers: "show:0", projection: new OpenLayers.Projection("EPSG:3857".toUpperCase()),}));

Voir ici pour les paramtères (ex. transparence, projection) à supporter : http://dev.openlayers.org/apidocs/files/OpenLayers/Layer/ArcGIS93Rest-js.html

**Comment by mbarbeau** [comment]
C'est implanté

6bd457d09020e902944d8c6268b24bb99a664edf

**Comment by mbarbeau** [comment]
Lien vers la doc:
https://github.com/infra-geo-ouverte/igo/blob/dev/doc/xml/DocumentationXML.markdown#arcgis93rest

**Comment by gignacnic** [comment]
@olibegin et @bosthy : vous pourrez maintenant l'utiliser de votre côté lorsque la https://github.com/infra-geo-ouverte/igo/compare/dev sera votre version d'IGO.
