### ISSUE TITLE
Ajouter le support d'une couche CartoDB dans le XML d'IGO

### ISSUE THREAD

**Issue by gignacnic** [infra-geo-ouverte/igo#120]
En se basant sur ce code de CartoDB dans OpenLayers : https://github.com/infra-geo-ouverte/igo/commit/3a8b299cd6410e6e482c973eb0754c74349a9078 cela permettrait d'ajouter des couches CartoDB dans IGO-Navigateur, voici un url de couche CartoDB à utiliser : 
https://gignacnic.cartodb.com/tables/obs_terrain/public

http://gis.stackexchange.com/questions/89910/cartodb-map-in-openlayers

**Comment by pelord** [comment]
Archivage du dépôt. Fermeture des issues/Pull requests
