### ISSUE TITLE
Doc d'installation 

### ISSUE THREAD

**Issue by nbtetreault** [infra-geo-ouverte/igo#14]
dans le readme.md on parle de l'installation avec Vagrant, mais pas de https://github.com/infra-geo-ouverte/igo/blob/master/doc/installation/installation_linux.md

Ça devrait être indiqué qu'on a plusieurs manières d'installer IGO.

**Comment by mbarbeau** [comment]
+1
- Faudrait mettre à jour la doc. 
- Ajouté une doc simplifiée, sans le pilotage.
- Retirer l'installation de apache, git, netbeans, et autres trucs qui ne sont pas spécifiques à IGO
- Faire une liste de prérequis à la place pour mapserver, psql, postgis, ...

**Comment by nbtetreault** [comment]
Un jour on aura un blogue pour y mettre les gugusses non spécifiques à IGO.

**Comment by infra-geo-ouverte** [comment]
@tremblaysimon  devrait s'en occuper car elle n'est pas à jour et devrait être revu.

**Comment by gignacnic** [comment]
la doc a été mise à jour ainsi que tous les types d'installations, reste celle avec wamp-windows.
