### ISSUE TITLE
Gestion des erreurs WMTS

### ISSUE THREAD

**Issue by mikesmichael** [infra-geo-ouverte/igo#145]
Je viens de faire une modification dans Igo (commit #144) pour permettre d'afficher un message générique à l'utilisateur quand une couche n'est pas disponible. J'aurais aimé appliquer le même principe au WMTS. Est-ce que quelqu'un est capable de le faire? Je n'ai pas trouvé où se fait le callback, j'ai cru comprendre que tout se passait dans le fichier openlayers.js et je n'ose pas ouvrir la librairie pour ça. La doc openlayers du WMTS n'a pas d'option de callback pour que je puisse trapper l'erreur. Je vais avoir besoin de votre aide pour celle là.

**Comment by pelord** [comment]
Archivage du dépôt. Fermeture des issues/Pull requests
