### ISSUE TITLE
Perte des numéros civiques dans l'outil d'itinéraire 

### ISSUE THREAD

**Issue by mikesmichael** [infra-geo-ouverte/igo#147]
Après une recherche dans l'outil d'itinéraire, les adresses avec numéro civique dans les inputs de recherche ainsi que celles définies dans le titre des marqueurs sont écrasées par une version sans numéro civique.

Pouvez-vous vérifier si c'est le service qui doit être adapté pour retourner le numéro civique ou si c'est plutôt les ligne 157, 158, 162 à 168 qui doivent être supprimés dans itineraire.js? 

[itineraire.js](https://github.com/infra-geo-ouverte/igo/blob/dev/interfaces/navigateur/public/js/app/menu/itineraire.js#L157)
![itineraire](https://cloud.githubusercontent.com/assets/9534827/14819030/3fb2ff8c-0b8e-11e6-949c-1b4fe437391e.png)

**Comment by mbarbeau** [comment]
Salut,

Juste supprimer les lignes ne seraient pas suffisants. Le lieu ne sera 
pas modifié si on déplace le point de départ ou d'arrivée. Faudrait 
faire un appel au GLO pour obtenir le numéro civique.

**Comment by mikesmichael** [comment]
Tu connais mieux le service que moi, est-ce que je peux te laisser regarder ça?

**Comment by mbarbeau** [comment]
Je peux regarder mais ça ne va pas être avant fin juin.

**Comment by mikesmichael** [comment]
Pas de problème.

**Comment by pelord** [comment]
Archivage du dépôt. Fermeture des issues/Pull requests
