### ISSUE TITLE
gestion des formats getinfo : dans ajout de service WMS

### ISSUE THREAD

**Issue by gignacnic** [infra-geo-ouverte/igo#171]
Quand un usager ajoute un service WMS dans la liste : "Ajout de service WMS" il doit pouvoir le configurer pour forcer l'info format comme dans le XML.
infoFormat="html"

Actuellement, cela n'est pas géré, ça prends le gml par défaut.

**Comment by bosthy** [comment]
Aussi la possibilité de passé par le proxy pour les sites sécurisées https

**Comment by gignacnic** [comment]
@bosthy : que veux-tu dire par un proxy pour les sites sécurisés en https? Est-ce relié au groupe outil "Ajout de service web" au haut à droite de la carte dans le navigateur comme #171 ? Cette partie de proxy désirée en https, serait une configuration par service ou propre à tous les services utilisées par le navigateur ?

**Comment by bosthy** [comment]
Quelqu'un chez nous a crée un nouveau service WMS sur un serveur https qui est déjà présent dans notre fichier de config.php comme service a l'interne (il connaissait son nouveau url WMS ) et il a ajoutée via l'outil "Ajout de service web"  dans le but de visualisé le nouveau service et on a eu une erreur. Je crois que votre outil accepte que les adresses public http.

**Comment by gignacnic** [comment]
OK, connais-tu un bon service WMS https disponible au grand public pour l'essayer, ça ne devrait pas causer problème en https, quelle erreur tu avais ?

**Comment by bosthy** [comment]
Mille excuses Nicolas, j'ai tester chez nous hier et ça semble fonctionner maintenant. J'ai pas eu d'erreur.
