### ISSUE TITLE
Documentation pour le module d'authentification

### ISSUE THREAD

**Issue by mikesmichael** [infra-geo-ouverte/igo#182]
Suite à la suggestion de Nicolas sur la liste Igo igo-dev. 

Si jamais vous avez l’occasion de documenter l’authentification, ce serait apprécié. Lorsque j'aurai terminé mon développement pour le partage de session pour l'authentification hors LDAP (sans PHP_AUTH_USER), J’y ferais des ajouts pour le documenter . Comme ça tout le monde sera en mesure de bien comprendre comment définir les configs. Je n’ai vu nulle part dans le git l’équivalent des commentaires qui sont dans le array « authentification » de votre configuration maison (même pas dans l’exemple du config dans le git), je pense que ça serait pertinent pour tous d’au moins retrouver cette information-là quelque part pour l’instant.

**Comment by pelord** [comment]
Archivage du dépôt. Fermeture des issues/Pull requests
