### ISSUE TITLE
Warning PHP

### ISSUE THREAD

**Issue by matrottier** [infra-geo-ouverte/igo#213]
Undefined offset: 1 in /igo/interfaces/navigateur/app/controllers/IgoController.php on line 467

**Comment by matrottier** [comment]
https://github.com/infra-geo-ouverte/igo/blob/dev/interfaces/navigateur/app/controllers/IgoController.php#L467

**Comment by pelord** [comment]
Archivage du dépôt. Fermeture des issues/Pull requests
