### ISSUE TITLE
Dessin de polygone troué, propriétés lignes non mise à jour 

### ISSUE THREAD

**Issue by mikesmichael** [infra-geo-ouverte/igo#230]
Lorsque l'on dessine un trou dans un polygone` this.lignes` n'est pas mis à jour à partir de modification de la géométrie modifée d'Openlayers. Les lignes réelles sont disponibles seulements dans l'éléments Openlayers sous `this._feature.components`. Donc lorsque l'on enregistre, on perd les trous, on n'a que les lignes créées à partir du constructeur. J'imagine que @mbarbeau tu seras plus à l'aise côté OpenLayers que moi pour trouver où corriger le problème. J'ai essayé de voir où je pourrais corriger ça mais en dehors du constructeur `Polygone`, je ne trouve pas où est mis à jour l'attribut.

**Comment by mbarbeau** [comment]
Bien vu, OpenLayers ne lance pas d'événement lorsqu'on crée un trou dans un polygon. J'ai appliqué un patch en dev.

**Comment by mikesmichael** [comment]
Ta correction fonctionne! Merci de ta rapidité!
