### ISSUE TITLE
Require.js vs .svn

### ISSUE THREAD

**Issue by mikesmichael** [infra-geo-ouverte/igo#24]
Petit problème pour toi @mbarbeau. Je pense que ça pourrait arriver à d'autres aussi.
En mettant mon code dans SVN à la FADQ, require.js va chercher mes fichiers js dans le répertoire .svn plutôt qu'à leur vraie emplacement. En cherchant sur le net, j'ai vue que ça serait possible d'ajouter le paramètre fileExclusionRegExp pour exclure les fichiers d'archive. J'ai voulu le tester mais je n'ai pas trouvé où sont les configs de require.
C'est le même genre de problème que ça:
http://stackoverflow.com/questions/20683471/excluding-svn-folders-when-optimising-with-requirejs.

Pour bien comprendre, voici ce que ça fait dans le fichier d'index généré. En plus les extensions sont tronqué alors même les fichier .svn-base ne sont pas lu correctement.
paths: {
            navigateur.js.svn-b: 'js/app/.svn/text-base/navigateur.js.svn-b',
        carte.js.svn-b: 'js/app/.svn/text-base/carte.js.svn-b',
        barreOutils.js.svn-b: 'js/app/.svn/text-base/barreOutils.js.svn-b',
                ...

Mon environnement de développement principale est hors svn, j'ai donc pu flusher les dossier .svn, Il n'y a pas d'urgence nationale à cette modif.

Merci

**Comment by mbarbeau** [comment]
J'ai apporté un correctif en début de semaine qui devrait régler ce problème en même temps. Met toi à jour et dis moi si tu as encore ce problème. 
Pourquoi mettre IGO dans svn ? Vous ne pouvez pas exclure le dossier?

**Comment by mikesmichael** [comment]
Merci pour la modif.

On met Igo dans SVN car nos applications web passent par là pour respecter notre principe de migration entre chaque environnement. 
Je t'explique comment on fonctionne:
Premièrement, le programmeur dépose son code dans son environnement personnel (dans mon cas miclan02), ensuite il commit le dans SVN, ce qui fait une copie dans un environnement pré-développement ou le code de tous les développeur se retrouve., C'est aussi là que le code contient les dossiers .svn. Quand le code est testé et fonctionnel, on le migrer dans l'environnement de dev pour les tests des analystes, ensuite en essai pour les tests des pilotes et finalement en prod pour les usagers. C'est lors de la migration dans l'environnement de dev que les .svn sont exclus de la copie du code. Mon problème est donc au niveau du code dans l'environnement de pré-dev où il se retrouve avec les .svn.

Notre code est présentement dans l'environnement de développement, quand il sera prêt à monter en essai je remettrai mon code à jour avec la version du github et je testerai ta modif.
