### ISSUE TITLE
mode="getCapabilities" donne des erreurs IE et Chrome

### ISSUE THREAD

**Issue by bosthy** [infra-geo-ouverte/igo#31]
Quatre adresses url de WMS publique avec mode="getCapabilities" donne des erreurs avec Chrome et IE pour FF c’est bon. Pour Chrome « infoEncodage » l’encodage n’est pas pris en compte dans la légende pour IE et FF c’est bon.

Mon fond de carte est en projection="EPSG:3857"

Lacs:
msWMSLoadGetMapParams(): WMS server error. Invalid SRS given : SRS must be valid for all requested layers.

![2015-06-03 09_50_10-igo](https://cloud.githubusercontent.com/assets/9865889/7961520/111ed00c-09d6-11e5-943d-b51959941094.png)

Exemple:
couche protocole="WMS" mode="getCapabilities" url="http://geogratis.gc.ca:80/geoserver/ows?"                 

couche protocole="WMS" mode="getCapabilities" url="http://wms.ess-ws.nrcan.gc.ca/wms/toporama?"                          

couche protocole="WMS" mode="getCapabilities" url="http://wms.atlas.nrcan.gc.ca/wms/atlaswms_fr?"

couche protocole="WMS" mode="getCapabilities" url="http://ngwd-bdnes.cits.nrcan.gc.ca/service/ngwds/en/wms/ngwd-wms/ww_wms?"

**Comment by mbarbeau** [comment]
1 et 2) Seulement la légende qui ne fonctionne pas. On dirait que les wms ne supportent pas le getLegendGraphic pour la plupart des couches.

3) Pour l'encodage, tu peux ajouter 'encodage=ISO-8859-1'. Par contre, ça ne marchera pas plus car la projection par défaut de notre carte n'est pas supportée par le wms.

4) Erreur serveur sur le getMap...

Bref, ce n'est pas vraiment des erreurs de l'application...
