### ISSUE TITLE
Internationalisation

### ISSUE THREAD

**Issue by ymoisan** [infra-geo-ouverte/igo#76]
La présente est plus une suggestion qu'un signalement de bogue en tant que tel.  Dans la mesure où la survie d'un projet d'informatique libre passe par la formation d'une communauté (de développeurs, d'utilisateurs, de traducteurs, etc.), il me semble que le choix de nommer des fonctions ou des balises XML en français limite énormément le potentiel de créer une communauté en dehors du monde francophone.  Qu'on me comprenne bien : le français est ma langue maternelle et j'en ai toujours été un ardent défenseur, mais un projet d'informatique libre doit être codé et documenté d'abord en anglais, si l'on veut une réelle participation communautaire.  

Le plus important toutefois, au chapitre de l'internationalisation, c'est de s'assurer que les chaînes de caractères soient découplées du code.  Exemple de https://github.com/infra-geo-ouverte/igo/blob/master/edition/app/services/FeatureService.php :

public function getAuthenticationErrorMessage(){  
        return array("result" => "error", "error" => "Vous n'êtes pas identifié par le système.");
    }

Un utilitaire comme gettext permet de traduire dynamiquement des chaînes de caractère en fonction de la langue de l'usager.  Dans l'exemple précédent, le message sera toujours en français, indépendamment de la locale du système ou du fureteur de l'usager, parce qu'il est couplé au code.  Les chaînes de caractères sont dans des fichiers texte (des .po dans le cas de gettext), lesquels fichiers peuvent être modifiés localement puis retournés au projet ou, encore mieux, être gérés par un truc comme Transifex (comme QGIS le fait par exemple pour gérer ses quelque 50 traductions).

Il faudrait aussi éviter de stocker de l'information dans des formats de fichiers propriétaires.  J'ai vu des .docx à quelques endroits.  Un PDF à la limite, mais idéalement du texte : markdown, reStructuredtext, etc.

**Comment by ymoisan** [comment]
Au sujet de la documentation, pourquoi ne pas tabler sur l'imposante liste de services ("hooks") de GitHub (https://github.com/github/github-services/tree/master/lib/services), dont celui vers ReadTheDocs (RTD) ?  Pour les projets GitHub ouverts, RTD est gratuit.  La seule "contrainte", c'est d'accepter d'écrire de la documentation dans un format texte qui s'apparente à un langage "markup" plutôt que dans un logiciel de traitement de texte conventionnel.  Exemples de manuels de l'utilisateur de QGIS : 
- QGIS, version en développement : résultat (http://docs.qgis.org/testing/en/docs/user_manual/) et source\* (https://github.com/qgis/QGIS-Documentation/tree/master/source/docs/user_manual)
- QGIS 2.8 (version stable actuelle) : résultat (http://docs.qgis.org/2.8/en/docs/user_manual/) et source (https://www.transifex.com/qgis/qgis-documentation/)

Contrairement à une documentation dans un format binaire comme .docx, par exemple, la documentation en format texte (reStructuredText idéalement) est :
- légère (en termes de Ko)
- facilement versionnable (conséquence directe du fait que le format est du texte simple) dans un outil comme GitHub
- (plus) facilement traduisible (modulo une arborescence de fichiers .rst et de saisies d'écran dans des répertoires comme fr-CA, en-US, etc.)
- lisible par n'importe quel éditeur de texte
- et surtout, et là je vais faire le plus hideux des anglicismes, "repurposeable".

Ce dernier point mérite qu'on s'y attarde un peu.  Avec une documentation en reST, un outil comme RTD (Sphinx derrière) génère par défaut un "site web" (avec table des matières, boîte de recherche, etc.), mais on peut également exporter en PDF ou en ePub dynamiquement.  Les formats de sortie possibles sont listés à http://sphinx-doc.org/.

Vos développeurs pourraient même s'amuser à installer Sphinx et à récupérer la documentation reST d'IGO sur GitHub, le cas échéant, pour générer la documentation localement en essayant qui les nouvelles versions de Sphinx, qui de nouvelles feuilles de styles, etc.
- Notez tout en bas des sites web qui contiennet les manuels de QGIS une mention "Textual error, missing text or you know better: fix me".  L'hyperlien "Fix Me" renvoie sur Transifex pour QGIS 2.8 et sur le projet GitHub de documentation de QGIS pour la version en développement.  Les fichiers de documentation sont des .rst (reStructuredText).

**Comment by nbtetreault** [comment]
Ce sont des bonnes idées et vos explications sont bien détaillé. Nous les prendrons en compte.

**Comment by ymoisan** [comment]
https://www.transifex.com/blog/2015/localization-101-a-beginners-guide-to-software-localization/
On n'aborde pas la façon de localiser less chaînes de caractères dans le code php (ex. avec gettext), mais on présente bien le processus de L10N/I18N.

**Comment by pelord** [comment]
Archivage du dépôt. Fermeture des issues/Pull requests
