### ISSUE TITLE
félicitations

### ISSUE THREAD

**Issue by joejoseph00** [infra-geo-ouverte/igo#78]
Félicitations au gouvernement du Québec pour avoir ouvert le code source pour ce projet et pour avoir choisit des plateformes/bibliothèques plus libres que certains autres.

Voici deux liens qui pourrait se trouver utile pour d'autres initiatives gouvernementaux en logiciel libre https://github.com/open-data (parent projet du ckanext)
et 
https://github.com/open-data/ckanext-canada (hébergement et distribution des données dans plusieurs formes)
et
http://drupal.org/project/wetkit  (système de gestion du contenu web dont je suis un des contributeurs)

petit irritation: en fouillant dans votre repo j'ai remarqué des fichiers .xlsx et .docx , et un .swf (en binaire) des formats parfois moins commode dans le monde du logiciel libre.  Si vous pouvez remplacer ces formats par des formats plus libres encore ça sera encore mieux.  En gros ce projet m'intéresse et je vais garder un œil ouvert là dessus.

Merci beaucoup et bonne journée

**Comment by gignacnic** [comment]
Merci de l'intérêt. Évidemment, la gestion des données ouvertes sont très bien supportées par IGO-Navigateur (http://igouverte.org/demo/) comme vous avez pu le voir dans le communiqué officiel du MSP (caserne, territorie agricole, village relais, ilôt de chaleur): http://www.securitepublique.gouv.qc.ca/ministere/salle-presse/communiques/communiques.html?tx_ttnews%5Btt_news%5D=12517  Justement, CKAN et son extensions géomatique (https://github.com/ckan/ckanext-spatial) ne sont pas assez puissantes et flexibles pour nos besoins. C'est pour quoi IGO est une bonne solution complémentaire à la visualisation et la gestion de données de géomatique avec d'autres outils comme CKAN. Concernant les .docx, on en a conservé certains, car des utilisateurs d'IGO ne sont pas tous des développeurs et dans certains cas ce format était le meilleure compromis. Pour ce qui est du fichier .xlsx, lequel ? Car je ne le trouve pas dans le dépôt. Merci encore de l'intérêt.

**Comment by mbarbeau** [comment]
Pour le .xlsx, je l'ai supprimé. C'était un vieux document de gestion des issues...

**Comment by pelord** [comment]
Archivage du dépôt. Fermeture des issues/Pull requests
